[project]
name = "post-secret-archive"
version = "0.1.0"
description = "A web application to search through the Post Secret archive."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.0",
    "flask>=3.1.2",
]
